# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56006a8bb7ba0890ed5aea5ad740e5ef"
name = "commercial-supply-app"
handle = "commercial-supply-app-9"
application_url = "https://hardwood-sa-qualities-scenes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-hydrogen-asad.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hardwood-sa-qualities-scenes.trycloudflare.com/auth/callback",
  "https://hardwood-sa-qualities-scenes.trycloudflare.com/auth/shopify/callback",
  "https://hardwood-sa-qualities-scenes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
